name: Deploy Pages

on:
  push:
    paths:
    - 'content/**'
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest    
    outputs:
      changed: ${{ steps.changed.outputs.test }}
      changed2: ${{ steps.changed.outputs }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public
        HUGO_VERSION: 0.57.2
        BUILD_SCRIPT: |
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
          dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
          git submodule update --init
          hugo -v
    - name: get-changed-files
      id: changed
      uses: lots0logs/gh-action-get-changed-files@2.0.6
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
  tweet:
    run-os: ubuntu-latest
    needs: deploy
    steps:
    - name: test
      run: echo ${{ needs.deploy.outputs.changed }}
    - name: test2
      run: echo ${{ needs.deploy.outputs.changed2 }}
    - name: Tweet
      uses: xorilog/twitter-action@0.1
      with:
        args: "-message test"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
