name: CI

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest    
    steps:
    - name: Install hugo
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
        sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
    - uses: actions/checkout@v1
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: git submodule update --init && hugo -v
